SC-647-casetype-destruction
wavesplatform/Waves pull request #3235
Opened 2020-08-13 18:24 UTC by potan

Impruve match/case
1. Use constants
2. Dectruction caseType

2020-10-23 09:13 UTC, finnoio requested changes

2020-10-23 09:13 UTC, finnoio commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ExpressionCompiler.scala
> +      exprTypes = typedExpr.t //exprTypesWithErr._1.getOrElse(NOTHING)
remove comments

2020-10-23 09:13 UTC, finnoio commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ExpressionCompiler.scala
> +      errorList = /*exprTypesWithErr._2 ++*/ ifCasesWithErr._2 ++ compiledMatch.errors ++ checkWithErr._2
remove comment

2020-10-23 09:13 UTC, finnoio commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ExpressionCompiler.scala
> +                }*/
remove commented lines

2020-10-23 09:13 UTC, finnoio commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Expressions.scala
> +      //caseType: Type,
remove commented lines

2020-10-23 09:13 UTC, finnoio commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
> +                //caseType = types,
remove commented lines

2020-10-26 14:00 UTC, xrtm000 requested changes
Seems strange that works this code
```
match (if true then "string" else 1) {
  case "string" => "yes"
  case _        => "no"
}
```
and such one
```
match (if true then "string" else 1) {
  case 1 => "yes"
  case _ => "no"
}
```
but if we define both possible values
```
match (if true then "string" else 1) {
  case "string" => "yes"
  case 1        => "no"
}
```
compilation will be failed with enigmatic error: _"Matching not exhaustive: **possibleTypes are String, Int, while matched are String, Int**"_

2020-10-26 14:13 UTC, xrtm000 commented
Should we support mix of destructions? 
```
match (5, PointC(1)) {
  case (5, PointC(YB=1)) => "yes"
  case _                 => "no"
}
```
```
match PointC(1) {
  case PointC(YB=1) | PointC(YB=2) => "yes"
  case _                           => "no"
}
```
It might be useful, but currently it is not supported.

2020-10-26 14:20 UTC, xrtm000 requested changes

2020-10-26 14:20 UTC, xrtm000 commented on lang/tests/src/test/scala/com/wavesplatform/lang/ScriptParserTest.scala
> +  ignore("pattern matching with invalid case - expression in variable definition") {
Please, adapt this test

2020-10-26 14:27 UTC, xrtm000 commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/parser/Parser.scala
> +              case (false, false) => Pattern(Some(PART.INVALID(Pos(start, end), "destructed tuple is not fully typed")), Some(Tuple(Seq())), pats, Seq())
Please add test that rises "destructed tuple is not fully typed" error

2020-12-28 13:37 UTC, closed without merging

2020-12-28 13:37 UTC, mrkraft commented
Unfinished