Sc 625 estimate spent complexity by block 1
wavesplatform/Waves pull request #3244
Opened 2020-08-18 17:39 UTC by potan

2020-09-09 07:57 UTC, finnoio approved these changes

2020-10-26 16:02 UTC, xrtm000 requested changes
Add tests for various script types and negative scenarios

2020-12-28 13:30 UTC, mrkraft commented
Unfinished

2020-12-28 13:31 UTC, closed without merging

2020-12-28 13:31 UTC, mrkraft commented
Unfinished