SC-668 Add DeleteEntry to V4 composite type
wavesplatform/Waves pull request #3266
Opened 2020-09-13 09:28 UTC by xrtm000

2020-09-21 12:26 UTC, potan approved these changes

2020-09-24 08:11 UTC, finnoio approved these changes

2020-10-13 13:22 UTC, msmolyakov requested changes

2020-10-26 08:52 UTC, xrtm000 commented on lang/tests/src/test/scala/com/wavesplatform/lang/compiler/package.scala
> +        WavesContext.build(DirectiveSet(v, Account, Expression).explicitGet()),
Because there could not be DataTransaction for asset expression and tx value for DApp

2020-10-26 08:52 UTC, xrtm000 commented on lang/tests/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
> +        | getBinaryValue(entries, 4)          == base58'a'
Added

2020-10-26 10:14 UTC, msmolyakov approved these changes

2020-10-28 08:57 UTC, mrkraft approved these changes

2020-10-28 08:57 UTC, merged