SC-658-decompiller-add-brackets
wavesplatform/Waves pull request #3268
Opened 2020-09-15 14:09 UTC by potan

Add brackets when IF operator place in expression.

2020-10-26 09:47 UTC, xrtm000 requested changes
It is a special case.
Decompile of `(if(condition) then obj1 else obj2).field` also returns `if(condition) then obj1 else obj2.field`

2020-11-18 10:13 UTC, xrtm000 approved these changes

2020-11-25 08:50 UTC, mrkraft approved these changes

2020-12-04 08:53 UTC, msmolyakov approved these changes

2020-12-10 14:15 UTC, merged