SC-663-api-add-contiuations-list
wavesplatform/Waves pull request #3275
Opened 2020-09-29 16:15 UTC by potan

2020-09-29 21:21 UTC, xrtm000 requested changes
Test in ContinuationSuite

2020-09-29 21:21 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
> +          case t: smart.InvokeScriptTransaction => Json.obj("сontinuationTtansactionIds" -> commonApi.continuations(t.id()).map(_.toString))
```suggestion
          case t: smart.InvokeScriptTransaction => Json.obj("сontinuationTransactionIds" -> commonApi.continuations(t.id()).map(_.toString))
```

2020-09-29 21:21 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
> +          case t: smart.ContinuationTransaction => Json.obj("сontinuationTtansactionIds" -> commonApi.continuations(t.invokeScriptTransactionId).map(_.toString))
```suggestion
          case t: smart.ContinuationTransaction => Json.obj("сontinuationTransactionIds" -> commonApi.continuations(t.invokeScriptTransactionId).map(_.toString))
```

2020-10-02 08:20 UTC, xrtm000 requested changes

2020-10-02 08:20 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
> +      case t: smart.InvokeScriptTransaction => Json.obj("сontinuationTransactionIds" -> commonApi.continuations(t.id()).map(_.toString))
It is unnecessary field for old InvokeScript transactions that don't support continuations. Introduce InvokeScript transaction V3 to distinguish.

2020-10-08 16:10 UTC, xrtm000 requested changes
Please, add also **feeAssetId**, **version** and **height** fields

2020-10-16 09:04 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/transaction/serialization/impl/ContinuationTxSerializer.scala
> +      "version"                   -> 1,
Maybe add this field directly to ContinuationTransaction class?

2020-10-21 09:18 UTC, xrtm000 commented
And test new fields, please

2020-10-26 17:25 UTC, xrtm000 requested changes
Please, add height and test new fields

2020-11-01 19:03 UTC, xrtm000 commented
Test **dApp** and **call** fields

2020-11-12 10:17 UTC, xrtm000 approved these changes

2020-11-13 15:01 UTC, mrkraft approved these changes

2020-11-13 15:01 UTC, merged