Doc 744 base58
wavesplatform/Waves pull request #3290
Opened 2020-10-15 07:18 UTC by elenaili

- base58 patterns
- add security to /transactions/sign/{signerAddress}
- delete 403 response from /utils/seed/, /debug/validate
- extend description for /debug/stateHash/{height}

2020-11-06 10:28 UTC, phearnot approved these changes

2020-11-20 10:15 UTC, msmolyakov commented
https://github.com/wavesplatform/Waves/blob/a9ea6c8e14abe0009c6d1d5e2b14ccbff3307b54/node/src/main/resources/swagger-ui/swagger.json#L527
Not all data, but for array of specified keys.

2020-11-20 10:54 UTC, msmolyakov commented
https://github.com/wavesplatform/Waves/blob/a9ea6c8e14abe0009c6d1d5e2b14ccbff3307b54/node/src/main/resources/swagger-ui/swagger.json#L3955

Forever or for a specific time?

2020-11-20 11:05 UTC, msmolyakov requested changes

2020-11-20 15:23 UTC, msmolyakov requested changes

2020-11-20 15:23 UTC, msmolyakov commented on node/src/main/resources/swagger-ui/swagger.json
> +        "description": "Get detailed information about given assets. See [fields descriptions](https://docs.waves.tech/en/blockchain/token/#custom-token-parameters)",
What's the limit for assets count?

2020-11-21 09:01 UTC, msmolyakov approved these changes

2020-11-22 07:57 UTC, elenaili commented on node/src/main/resources/swagger-ui/swagger.json
> +        "description": "Get detailed information about given assets. See [fields descriptions](https://docs.waves.tech/en/blockchain/token/#custom-token-parameters)",
limits are not set yet

2020-11-30 11:02 UTC, merged