NODE-2273: /utils/script/evaluate API route
wavesplatform/Waves pull request #3305
Opened 2020-11-16 10:38 UTC by Karasiq

2020-12-07 09:21 UTC, phearnot approved these changes

2020-12-09 17:12 UTC, DrBlast requested changes
endpoint utils/script/evaluate/{address} not availiable and not added to swagger

2020-12-10 14:48 UTC, DrBlast approved these changes

2020-12-10 14:48 UTC, DrBlast commented on node/src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
> +  routePath("/script/evaluate/{address}") in {
add tests for different types of function args: String, ByteVector, List[String|ByteVector|Boolean|Int]

2020-12-10 14:55 UTC, DrBlast requested changes

2020-12-10 14:55 UTC, DrBlast commented on node/src/test/scala/com/wavesplatform/http/UtilsRouteSpec.scala
> +    val testScript = {
add tests for different types of function args: String, ByteVector, List[String|ByteVector|Boolean|Int]

2020-12-14 16:58 UTC, DrBlast approved these changes

2020-12-14 16:59 UTC, merged