NODE-2269: Check address seq range (REST API)
wavesplatform/Waves pull request #3307
Opened 2020-11-24 17:26 UTC by Karasiq

2020-12-01 09:15 UTC, phearnot approved these changes

2020-12-01 10:47 UTC, msmolyakov requested changes

2020-12-01 10:47 UTC, msmolyakov commented on node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
> +      responseAs[JsObject] shouldBe Json.obj("error" -> 10, "message" -> "Too big sequences requested")
1. `sequences` -> `sequence`
2. Let's tell user in the error text what is the limit

2020-12-01 10:47 UTC, msmolyakov commented on node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
> +      responseAs[JsObject] shouldBe Json.obj("error" -> 10, "message" -> "Too big sequences requested")
Why "too big sequence"? Еhe order of values is incorrect, but the range is not exceeded

2020-12-03 09:40 UTC, msmolyakov approved these changes

2020-12-03 09:41 UTC, merged