NODE-2268: Fix assets distribution limit and depth checks (REST API)
wavesplatform/Waves pull request #3308
Opened 2020-11-25 17:46 UTC by Karasiq

2020-11-30 08:54 UTC, phearnot approved these changes

2020-12-01 11:00 UTC, msmolyakov requested changes

2020-12-01 11:00 UTC, msmolyakov commented on node/src/test/scala/com/wavesplatform/http/RestAPISettingsHelper.scala
> +           |  distribution-address-limit = $MaxAddressesPerRequest
is this necessary to rename existing config parameter? What about backward compatibility?

2020-12-01 11:05 UTC, msmolyakov commented on node/src/test/scala/com/wavesplatform/http/RestAPISettingsHelper.scala
> +           |  distribution-address-limit = $MaxAddressesPerRequest
this is typo in test config

2020-12-01 11:05 UTC, msmolyakov approved these changes

2020-12-01 11:10 UTC, merged