Sc 685 sync chains parser
wavesplatform/Waves pull request #3309
Opened 2020-11-27 11:03 UTC by mrkraft

2020-11-30 16:31 UTC, xrtm000 requested changes
Please, add evaluation test checking strictness

2020-12-02 17:25 UTC, xrtm000 requested changes

2020-12-02 17:25 UTC, xrtm000 commented on lang/tests/src/test/scala/com/wavesplatform/lang/EvaluatorV2Test.scala
> +        |
Please, add something like
```
func testFunc() = {
 strict a = throw("error")
 true
}
testFunc()

```
and check if error is raised

2020-12-03 14:46 UTC, potan approved these changes

2020-12-09 09:12 UTC, xrtm000 approved these changes

2020-12-16 15:07 UTC, finnoio approved these changes

2020-12-18 14:51 UTC, merged