SC-687-crosscontract-invoke
wavesplatform/Waves pull request #3316
Opened 2020-12-08 15:52 UTC by potan

2020-12-25 23:14 UTC, xrtm000 requested changes

2020-12-25 23:14 UTC, xrtm000 commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +        fee     <- ciFee(1)
Why is it enough despite issuing via action?
See line 2330:
https://github.com/wavesplatform/Waves/pull/3316/files#diff-7a87dd14a82b2cd0e58fddefc26230665e583d933ab5ba4da3ea943f13f4a7f1R2330

2020-12-25 23:14 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala
> +                  13
What is it? Should be it tested?

2020-12-25 23:14 UTC, xrtm000 commented on node-it/src/test/scala/com/wavesplatform/it/api/model.scala
> +object Invokation {
```suggestion
object Invocation {
```

2020-12-25 23:14 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/InvokeScriptResult.scala
> +      InvokeScriptResult(/*x.data ++ y.data, x.transfers ++ y.transfers,*/ invokes = x.invokes ++ y.invokes)
Should it be saved unchanged?

2020-12-28 09:41 UTC, potan commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +        fee     <- ciFee(1)
I use NFT

2020-12-28 10:06 UTC, xrtm000 commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +        fee     <- ciFee(1)
If set Issue action as non-NFT there still will no be an error

2020-12-28 15:53 UTC, potan commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala
> +                  13
It limits nested Invoke. Tests "Infilite recurcive crosscontract call".

2020-12-28 15:54 UTC, potan commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +        fee     <- ciFee(1)
Fixed

2020-12-28 20:23 UTC, merged