Sc 687 fee for issue test
wavesplatform/Waves pull request #3336
Opened 2020-12-29 13:56 UTC by potan

2021-01-25 17:04 UTC, xrtm000 requested changes

2021-01-25 17:04 UTC, xrtm000 commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +    def contract1(otherAcc: Address, alias: Alias): DApp = {
This duplicates 
https://github.com/wavesplatform/Waves/pull/3336/files#diff-7a87dd14a82b2cd0e58fddefc26230665e583d933ab5ba4da3ea943f13f4a7f1R2463

2021-02-18 14:21 UTC, xrtm000 approved these changes
Mentioned above code duplication is actual

2021-02-20 08:07 UTC, msmolyakov approved these changes

2021-03-03 14:27 UTC, mrkraft approved these changes

2021-03-10 07:58 UTC, merged