Sc 716 increase payments limit
wavesplatform/Waves pull request #3364
Opened 2021-02-09 12:16 UTC by potan

2021-02-11 09:16 UTC, msmolyakov approved these changes

2021-02-18 16:15 UTC, xrtm000 requested changes
Where is the check that total complexity doesn't exceed 52000?

2021-02-18 16:15 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptDiff.scala
> +          _          <- TracedResult(Either.cond(payments.payments.size <= version.maxPayments, (), GenericError(s"Script payment amount=${payments.payments.size} should not exceed ${version.maxPayme
Why is it needed? `AttachedPaymentExtractor.extractPayments` contains this check

2021-03-17 14:57 UTC, xrtm000 approved these changes

2021-03-18 09:08 UTC, merged