SC-718 BigInt
wavesplatform/Waves pull request #3371
Opened 2021-02-25 16:56 UTC by potan

2021-03-17 09:18 UTC, msmolyakov approved these changes

2021-03-17 21:12 UTC, xrtm000 requested changes
Add tests for `toBytesBigInt`, check that `powBigInt` and `logBigInt` don't allow to exceed BigInt limits

2021-03-17 21:12 UTC, xrtm000 commented on lang/tests/src/test/scala/com/wavesplatform/lang/IntegrationTest.scala
> +    eval(src, version = V4) shouldBe Right(CONST_LONG(Long.MaxValue-1))
Fix of median should be started from V5

2021-03-17 21:12 UTC, xrtm000 commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
> +        .filterOrElse(v => v <= maxBigInt && v >= minBigInt, "Value to big for 512-bits big integer")
```suggestion
        .filterOrElse(v => v <= maxBigInt && v >= minBigInt, "Value too big for 512-bits big integer")
```

2021-03-17 21:12 UTC, xrtm000 commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
> +    NativeFunction("parseBigInt", 65, STRING_TO_BIGINTOPT, BIGINT, ("n", STRING)) {
```suggestion
    NativeFunction("parseBigInt", 65, STRING_TO_BIGINTOPT, UNION(BIGINT, UNIT), ("n", STRING)) {
```

2021-03-17 21:12 UTC, xrtm000 commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
> +      case CONST_BYTESTR(ByteStr(n)) :: CONST_LONG(off) :: CONST_LONG(s) :: Nil => Either.cond(off >= 0 && off <= n.size && s <= 64 && s > 0, CONST_BIGINT(BigInt(n.slice(off.toInt, (off+s).toInt))),
```suggestion
      case CONST_BYTESTR(ByteStr(n)) :: CONST_LONG(off) :: CONST_LONG(s) :: Nil => Either.cond(off >= 0 && off <= n.size && s <= 64 && s > 0, CONST_BIGINT(BigInt(n.slice(off.toInt, (off+s).toInt))), s"ByteStr too long ($s > 64 bytes)")
```

2021-03-17 21:12 UTC, xrtm000 commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
> +      case CONST_BYTESTR(ByteStr(n)) :: Nil => Either.cond(n.size <= 64, CONST_BIGINT(BigInt(n)), s"ByteStr too long (s{n.size} > 64 bytes)")
```suggestion
      case CONST_BYTESTR(ByteStr(n)) :: Nil => Either.cond(n.size <= 64, CONST_BIGINT(BigInt(n)), s"ByteStr too long (${n.size} > 64 bytes)")
```

2021-03-22 09:22 UTC, alexeykiselev requested changes

2021-03-22 09:22 UTC, alexeykiselev commented on lang/doc/v5/funcs/operators.hjson
> +      doc: "Substitute integers."
`Substitute integers` -> `Subtract integers`

2021-03-22 09:22 UTC, alexeykiselev commented on lang/doc/v5/funcs/operators.hjson
> +      doc: "Substitute big integers."
Substitue -> Subtract

2021-03-25 11:36 UTC, xrtm000 approved these changes

2021-03-26 11:12 UTC, mrkraft approved these changes

2021-03-26 11:13 UTC, merged