SC-738-v5-limits
wavesplatform/Waves pull request #3398
Opened 2021-03-23 13:22 UTC by potan

Actions and data counts.

2021-03-25 15:23 UTC, msmolyakov approved these changes

2021-03-29 16:47 UTC, xrtm000 requested changes

2021-03-29 16:47 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/http/UtilsApiRoute.scala
> +              avaliableData = ContractLimits.MaxWriteSetSize(V5),
```suggestion
              avaliableData = ContractLimits.MaxWriteSetSize(script.stdLibVersion),
```

2021-03-29 16:47 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/http/UtilsApiRoute.scala
> +              avaliableActions = ContractLimits.MaxCallableActionsAmount(V5),
```suggestion
              avaliableActions = ContractLimits.MaxCallableActionsAmount(script.stdLibVersion),
```

2021-03-29 16:47 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptDiff.scala
> +              case ScriptResultV4(actions, unusedComplexity, ret) =>
Code below seems as duplication from `case ScriptResultV3` block. Please, extract to method and reuse if it possible

2021-03-29 16:47 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptTransactionDiff.scala
> +              case ScriptResultV4(actions, unusedComplexity, _) =>
Seems as duplication

2021-03-29 16:47 UTC, xrtm000 commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptV5LimitsTest.scala
> +//import org.scalatest.exceptions.TestFailedException
Remove commented imports

2021-03-29 20:55 UTC, xrtm000 approved these changes

2021-03-30 07:33 UTC, mrkraft approved these changes

2021-03-30 07:34 UTC, merged