SC-753 Additional small verifier tests
wavesplatform/Waves pull request #3443
Opened 2021-04-19 15:03 UTC by xrtm000

2021-04-27 11:16 UTC, msmolyakov requested changes

2021-04-27 11:16 UTC, msmolyakov commented on node/src/test/scala/com/wavesplatform/http/AddressRouteSpec.scala
> +      (response \ "complexity").as[Long] shouldBe 0
should there be assertion for the `version` field as in the tests above?

2021-04-27 19:32 UTC, msmolyakov approved these changes

2021-04-28 08:39 UTC, mrkraft approved these changes

2021-04-28 08:39 UTC, merged