SC-762 Add self-state functions
wavesplatform/Waves pull request #3450
Opened 2021-04-21 17:17 UTC by xrtm000

2021-04-27 19:54 UTC, msmolyakov requested changes

2021-04-27 19:54 UTC, msmolyakov commented on lang/doc/v5/funcs/account-self-data-storage-functions.hjson
> +      doc: "Gets an array of bytes by key."
Gets from where?

2021-04-28 14:12 UTC, msmolyakov approved these changes

2021-04-28 14:32 UTC, mrkraft approved these changes

2021-04-28 14:32 UTC, merged