SC-757 BigInt message fixes
wavesplatform/Waves pull request #3451
Opened 2021-04-23 15:49 UTC by xrtm000

2021-04-27 08:13 UTC, msmolyakov requested changes

2021-04-27 08:13 UTC, msmolyakov commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/evaluator/ctx/impl/PureContext.scala
> +      case xs => notImplemented[Id, EVALUATED]("fraction(value: BigInt, numerator: BigInt, denominator: BigInt, round: rounds)", xs)
I think `round: rounds` this also does not apply to Ride. Maybe this should be `round: DOWN|CEILING|...`.

2021-04-27 19:29 UTC, msmolyakov approved these changes

2021-04-28 08:40 UTC, mrkraft approved these changes

2021-04-28 08:40 UTC, merged