SC-768 Support strict with tuple
wavesplatform/Waves pull request #3464
Opened 2021-04-29 13:54 UTC by xrtm000

2021-04-29 14:24 UTC, msmolyakov requested changes

2021-04-29 14:24 UTC, msmolyakov commented on lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/StrictWithTupleTest.scala
> +        | # str.parseInt() == i && cond && bytes.size() == 0
why is this commented out?

2021-04-29 14:55 UTC, xrtm000 commented on lang/tests/src/test/scala/com/wavesplatform/lang/evaluator/StrictWithTupleTest.scala
> +        | # str.parseInt() == i && cond && bytes.size() == 0
Done

2021-04-30 10:50 UTC, DrBlast approved these changes

2021-05-11 09:07 UTC, mrkraft approved these changes

2021-05-11 09:08 UTC, merged