SC Generic blockchain context method
wavesplatform/Waves pull request #3500
Opened 2021-06-04 14:46 UTC by xrtm000

2021-06-04 15:54 UTC, vsuharnikov approved these changes

2021-06-08 09:31 UTC, phearnot requested changes
Please add a test which uses matcher's Blockchain implementation, which will check a script handling both orders and transactions. Transaction validation branch should access blockchain function, while order branch should not. Make sure exception is thrown for transaction and is not thrown for order.

2022-05-05 18:36 UTC, phearnot approved these changes

2022-05-05 18:36 UTC, phearnot approved these changes

2022-05-05 18:36 UTC, merged