Add RIDE V6
wavesplatform/Waves pull request #3505
Opened 2021-06-11 13:40 UTC by xrtm000

2021-08-13 13:43 UTC, DrBlast requested changes

2021-08-13 13:43 UTC, DrBlast commented on lang/doc/v6/funcs/verification-functions.hjson
> +        "RsaDigestAlgs"
add possible variants of RsaDigestAlgs

2021-08-17 10:03 UTC, DrBlast approved these changes

2021-08-18 14:22 UTC, xrtm000 commented on lang/doc/v6/funcs/verification-functions.hjson
> +        "RsaDigestAlgs"
Done

2021-08-19 09:01 UTC, mrkraft approved these changes

2021-08-19 09:01 UTC, merged