SC-785 Free call
wavesplatform/Waves pull request #3516
Opened 2021-06-28 19:21 UTC by xrtm000

2021-09-22 18:54 UTC, DrBlast requested changes

2021-09-22 18:54 UTC, DrBlast commented on node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/freecall/InvokeExpressionSuite.scala
> +    val txFromUnconfirmed = sender.utx().find(_.id == id).get
remove this check, test may be unstable

2021-09-23 09:19 UTC, xrtm000 commented on node-it/src/test/scala/com/wavesplatform/it/sync/smartcontract/freecall/InvokeExpressionSuite.scala
> +    val txFromUnconfirmed = sender.utx().find(_.id == id).get
Done

2021-09-27 14:18 UTC, mrkraft approved these changes

2021-09-27 14:23 UTC, phearnot approved these changes

2021-09-27 14:23 UTC, merged