NODE-2362: New data entries limit calculation
wavesplatform/Waves pull request #3588
Opened 2021-11-18 03:13 UTC by Karasiq

2021-12-27 15:24 UTC, yvaskov requested changes

2021-12-27 15:24 UTC, yvaskov commented on node/src/test/scala/com/wavesplatform/transaction/data/DataTransactionNewLimitsSpec.scala
> +
Add negative tests (just in case): 
- key > 400 bytes
- value > 32767 bytes
- overall data > 165835 bytes (with keys <= 400 and data <= 32767)

2021-12-28 08:58 UTC, yvaskov approved these changes

2022-01-10 10:59 UTC, phearnot approved these changes

2022-01-10 13:59 UTC, merged