NODE-2365: Strictly require a public key hash to be 20 bytes long
wavesplatform/Waves pull request #3594
Opened 2021-11-29 22:26 UTC by Karasiq

2021-12-20 10:00 UTC, phearnot approved these changes

2021-12-20 14:35 UTC, yvaskov requested changes

2021-12-20 14:35 UTC, yvaskov commented on node/src/test/scala/com/wavesplatform/transaction/smart/EthereumTransactionSpec.scala
> +
Add a public key hash length check

2021-12-23 07:40 UTC, yvaskov approved these changes

2021-12-23 11:26 UTC, merged