NODE-2409 New script serialization methods
wavesplatform/Waves pull request #3606
Opened 2021-12-16 14:55 UTC by ivan-mashonskiy

2021-12-27 15:50 UTC, Karasiq requested changes

2021-12-27 15:50 UTC, Karasiq commented on lang/shared/src/main/scala/com/wavesplatform/lang/contract/serialization/ContractSerDeV2.scala
> +    (1 to len).toList.traverse[Either[String, *], A](_ => df(in))
`len` can be ill-formed and lead to allocation of Int.Max list

2021-12-27 15:50 UTC, Karasiq commented on lang/shared/src/main/scala/com/wavesplatform/lang/contract/serialization/ContractSerDeV2.scala
> +        case false => Right(None)
```suggestion
    tryEi(in.readRawByte().toInt)
      .flatMap {
        case 1 => df(in).map(_.some)
        case 0 => Right(None)
        case _ => ???
```

2021-12-27 15:50 UTC, Karasiq commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/compaction/ContractScriptCompactorV2.scala
> +      val compNameIdx = state.originalNames.indexOf(oldName)
indexOf is O(N) operation, so it's better to form a temporary hash map and operate with it.

2021-12-27 15:50 UTC, Karasiq commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/compaction/ContractScriptCompactorV2.scala
> +      val compNameIdx = state.originalNames.indexOf(oldName)
indexOf is O(N) operation, so it's better to form a temporary hash map and operate with it.

2021-12-27 15:50 UTC, Karasiq commented on lang/shared/src/main/scala/com/wavesplatform/lang/v1/compiler/ContractCompiler.scala
> +            resultDApp = ContractScriptCompactorV1.compact(resultDApp)
No need to keep the old compaction algorithm.

2022-01-10 09:39 UTC, Karasiq approved these changes

2022-01-14 08:59 UTC, yvaskov approved these changes

2022-01-14 10:59 UTC, xrtm000 approved these changes

2022-01-14 11:00 UTC, phearnot approved these changes

2022-01-14 11:00 UTC, merged