NODE-2412 Fix handle of modifying last block by blockchain updates
wavesplatform/Waves pull request #3618
Opened 2022-01-13 15:01 UTC by xrtm000

2022-01-14 00:07 UTC, Karasiq commented on grpc-server/src/main/scala/com/wavesplatform/events/Repo.scala
> +        db.put(keyForHeight(ls.keyBlock.height), solidified.protobuf.update(_.append.update(_.block.modify(_.copy(block = None)))).toByteArray)
```suggestion
        db.put(keyForHeight(ls.keyBlock.height), solidified.protobuf.update(_.append.block.optionalBlock := None)).toByteArray)
```

2022-01-14 15:11 UTC, xrtm000 commented on grpc-server/src/main/scala/com/wavesplatform/events/Repo.scala
> +        db.put(keyForHeight(ls.keyBlock.height), solidified.protobuf.update(_.append.update(_.block.modify(_.copy(block = None)))).toByteArray)
Done

2022-01-18 17:25 UTC, Karasiq requested changes

2022-01-18 17:25 UTC, Karasiq commented on grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
> +            while (repo.height == 5) {}
```suggestion
            while (repo.height == 5) Thread.sleep(10)
```

2022-01-18 17:25 UTC, Karasiq commented on grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
> +            while (!startRead) {}
```suggestion
            while (!startRead) Thread.sleep(10)
```

2022-01-18 17:25 UTC, Karasiq commented on grpc-server/src/test/scala/com/wavesplatform/events/BlockchainUpdatesSpec.scala
> +        while (suspend()) {}
```suggestion
        while (suspend()) Thread.sleep(10)
```

2022-01-19 21:41 UTC, Karasiq approved these changes

2022-02-10 07:58 UTC, DrBlast approved these changes

2022-02-11 13:29 UTC, phearnot approved these changes

2022-02-11 13:29 UTC, merged