Support underscore for directive values
wavesplatform/Waves pull request #3619
Opened 2022-01-13 15:15 UTC by xrtm000

2022-01-18 17:23 UTC, Karasiq requested changes

2022-01-18 17:23 UTC, Karasiq commented on lang/shared/src/main/scala/com/wavesplatform/lang/directives/DirectiveParser.scala
> +    P(CharIn("a-zA-Z0-9_\\-/\\., "))
Add unit tests for it

2022-01-20 08:29 UTC, xrtm000 commented on lang/shared/src/main/scala/com/wavesplatform/lang/directives/DirectiveParser.scala
> +    P(CharIn("a-zA-Z0-9_\\-/\\., "))
Done

2022-01-21 13:05 UTC, yvaskov approved these changes

2022-01-24 10:15 UTC, phearnot approved these changes

2022-01-24 10:15 UTC, merged