NODE-2410 Fix sync call in dapp verifier check
wavesplatform/Waves pull request #3623
Opened 2022-01-17 14:14 UTC by ivan-mashonskiy

2022-01-18 17:22 UTC, Karasiq requested changes

2022-01-18 17:22 UTC, Karasiq commented on node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
> +  property("synchronous calls are not allowed in dApp verifier function") {
Add tests for infinite recursion cases

2022-01-19 10:12 UTC, Karasiq approved these changes

2022-01-19 10:12 UTC, phearnot approved these changes

2022-01-19 14:48 UTC, yvaskov approved these changes

2022-01-19 15:32 UTC, merged