NODE-2427: Increase SetScript limit after V6
wavesplatform/Waves pull request #3633
Opened 2022-01-23 19:04 UTC by Karasiq

2022-01-28 07:26 UTC, yvaskov approved these changes

2022-03-17 09:43 UTC, yvaskov requested changes

2022-03-17 09:43 UTC, yvaskov commented on node/src/test/scala/com/wavesplatform/state/diffs/SetScriptTransactionDiffTest.scala
Add test for dynamic fee calculation:
- 1024 bytes should be 0.001 waves
- 1025 bytes should be 0.002 waves
- 32/160kb before/after V6 (max) - 0.032 and 0.16 waves respectively

2022-03-29 14:01 UTC, yvaskov approved these changes

2022-03-29 15:16 UTC, phearnot approved these changes

2022-03-29 15:17 UTC, merged