Portfolio errors as Either
wavesplatform/Waves pull request #3647
Opened 2022-02-22 08:59 UTC by xrtm000

2022-03-22 09:18 UTC, vsuharnikov requested changes

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/api/common/BalanceDistribution.scala
> +            findNextBalance()
Minor, how about a pattern matching? :)
```scala
adjustedBalanceE match {
  case Right(adjustedBalance) if currentHeight <= height && adjustedBalance > 0 => Some(address -> adjustedBalance)
  case _ => findNextBalance()
}
```

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/api/http/DebugApiRoute.scala
> +        .fold(_ => this.serializer, blockchain => this.serializer.copy(blockchain = blockchain))
This's interesting. Why can we ignore the fact that we aren't able to construct `CompositeBlockchain` (the first part of `fold`). This means we can't apply the `diff`, thus, the blockchain won't accept this transaction too.

It looks like we should return the error from this API in this case. Or add a comment, why this is not possible.

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/diffs/BlockDiffer.scala
> +      initialFeeFromThisBlock <- wrap(initialFeeFromThisBlockE)
Probably, `feeFromPreviousBlockE` and `initialFeeFromThisBlockE` should be lazy.

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
> +      feeDiff               <- feeDiffE.leftMap(GenericError(_))
Minor: here too. Probably, `matcherPortfolioE` and `feeDiffE` should be lazy.

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/diffs/MassTransferTransactionDiff.scala
> +          Diff.combine(u._1, v._1).map((_, u._2 + v._2))
It'd good to see what we combine here instead of numbers. I know, it is an old code here, but it is hard to read and understand :)

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptDiff.scala
> +              checkDiffBalances(diff, blockchainAfterEvaluation)
I see it throws an exception. I think, this is not good to mix exceptions and Either. But let it be for now.

2022-03-22 09:18 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
> +        }
I saw this patter multiple times. I think, we need a special method in `Portfolio` (if it hasn't)

2022-03-25 10:07 UTC, closed without merging

2022-04-04 08:41 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/common/BalanceDistribution.scala
> +            findNextBalance()
Done

2022-04-04 08:41 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/http/DebugApiRoute.scala
> +        .fold(_ => this.serializer, blockchain => this.serializer.copy(blockchain = blockchain))
Not actual currently

2022-04-04 08:42 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/BlockDiffer.scala
> +      initialFeeFromThisBlock <- wrap(initialFeeFromThisBlockE)
Why? It seems be used almost always.

2022-04-04 08:42 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/ExchangeTransactionDiff.scala
> +      feeDiff               <- feeDiffE.leftMap(GenericError(_))
Done

2022-04-04 08:42 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/MassTransferTransactionDiff.scala
> +          Diff.combine(u._1, v._1).map((_, u._2 + v._2))
Done

2022-04-04 08:43 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/invoke/InvokeScriptDiff.scala
> +              checkDiffBalances(diff, blockchainAfterEvaluation)
Refactored in #3597

2022-04-04 08:43 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
> +        }
Is it actual at the moment?)

2022-04-04 09:01 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/reader/CompositeBlockchain.scala
> +        }
We could add a task to backlog