NODE-2445 Increase MaxCallableActionsAmount to 100 for Ride V6
wavesplatform/Waves pull request #3660
Opened 2022-03-25 13:21 UTC by ivan-mashonskiy

2022-03-31 08:21 UTC, yvaskov requested changes

2022-03-31 08:21 UTC, yvaskov commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +    property(s"can't make more than ${ContractLimits.MaxCallableActionsAmount(version)} payments for V${version.id}") {
Replace `payments` with `ScriptTransfers`

2022-03-31 08:34 UTC, ivan-mashonskiy commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/InvokeScriptTransactionDiffTest.scala
> +    property(s"can't make more than ${ContractLimits.MaxCallableActionsAmount(version)} payments for V${version.id}") {
Done

2022-03-31 12:09 UTC, yvaskov approved these changes

2022-04-04 11:27 UTC, yvaskov approved these changes

2022-04-04 11:42 UTC, phearnot approved these changes

2022-04-04 11:42 UTC, merged