NODE-2474 Improve generator base target calculation
wavesplatform/Waves pull request #3714
Opened 2022-05-27 16:47 UTC by xrtm000

2022-07-05 08:18 UTC, ivan-mashonskiy approved these changes

2022-07-12 08:16 UTC, yvaskov requested changes
~~Specifying `initial-base-target` for `GenesisBlockGenerator` doesn't work. Keeps calculating its own base target~~
Docs bug

2022-07-12 09:10 UTC, yvaskov approved these changes

2022-07-22 08:53 UTC, yvaskov requested changes
Needs a fix to account for `miner` flag in ``DistributionItem(seedText: String, nonce: Int = 0, amount: Share, miner: Boolean = true)`` while calculating initial base target

2022-07-26 08:28 UTC, yvaskov approved these changes

2022-07-27 11:04 UTC, phearnot approved these changes

2022-07-28 10:26 UTC, merged