NODE-2516 Improve invoke fail/reject tests
wavesplatform/Waves pull request #3767
Opened 2022-09-27 10:28 UTC by ivan-mashonskiy

2022-10-05 08:27 UTC, vsuharnikov commented on node/src/test/scala/com/wavesplatform/features/RideV6FailRejectTest.scala
> +            ethInvokeTx = None
?

2022-10-05 11:31 UTC, vsuharnikov requested changes

2022-10-05 11:31 UTC, vsuharnikov commented on node/src/test/scala/com/wavesplatform/features/RideV6FailRejectTest.scala
> +            ethInvokeTx = None
A case for `EthereumTransaction` is missing.

2022-10-05 11:31 UTC, vsuharnikov commented on node/src/test/scala/com/wavesplatform/features/RideV6FailRejectTest.scala
> +          ethInvokeTx = None
A case for `EthereumTransaction` is missing.

2022-10-05 11:31 UTC, vsuharnikov commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/RideV5FailRejectTest.scala
> +    //  after RideV6 failing of negative balance check before execution of ScriptTransfer asset script always leads to invoke rejection
Do we have a task for this? Could you add a task number here, e.g. `NODE-XXXX`?

2022-10-05 11:55 UTC, vsuharnikov commented on node/src/test/scala/com/wavesplatform/features/RideV6FailRejectTest.scala
> +            ethInvokeTx = None
Well, EthereumTransaction doesn't have the second version, closing

2022-10-05 12:06 UTC, vsuharnikov commented on node/src/test/scala/com/wavesplatform/features/RideV6FailRejectTest.scala
> +          ethInvokeTx = None
Well, it is too hard to do (impossible?) :) Closing

2022-10-05 12:07 UTC, vsuharnikov approved these changes

2022-10-10 14:42 UTC, yvaskov approved these changes

2022-10-24 11:15 UTC, phearnot approved these changes

2022-10-24 11:16 UTC, merged