Fix description for rollback depth in openapi.yaml
wavesplatform/Waves pull request #3773
Opened 2022-10-10 15:13 UTC by xrtm000

2022-10-11 15:20 UTC, darksyd94 approved these changes

2022-10-13 00:08 UTC, DrBlast requested changes
wrong description:
lines 203 254
check description for limits in lines  530  555

add limits description for  
- POST/GET  /assets/details
- POST/GET /addresses/data/{address} 
- POST/GET /transactions/info/
- /transactions/merkleProof 
- /blocks/address/{address}/{start}/{end}
- GET /blocks/seq/{start}/{end}
- GET /blocks/headers/seq/{start}/{end}

2022-10-13 15:08 UTC, darksyd94 approved these changes

2022-10-20 08:52 UTC, DrBlast approved these changes

2022-10-27 11:45 UTC, phearnot approved these changes

2022-10-27 11:45 UTC, merged