NODE-2567 State snapshot hash computation
wavesplatform/Waves pull request #3824
Opened 2023-03-21 15:30 UTC by ivan-mashonskiy

2023-04-07 07:50 UTC, vsuharnikov approved these changes

2023-04-07 07:50 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/serialization/package.scala
> +      if (buf.limit() - buf.position() >= size) {
`buf.remaining() >= size` ?

2023-04-07 12:32 UTC, yvaskov requested changes
Add test for genesis block state hash computation
Add asset decimals to existing tests

2023-04-12 11:09 UTC, yvaskov approved these changes

2023-04-18 09:16 UTC, xrtm000 approved these changes

2023-04-19 07:13 UTC, phearnot approved these changes

2023-04-19 07:13 UTC, merged