NODE-2609 Light node implementation
wavesplatform/Waves pull request #3874
Opened 2023-09-01 17:40 UTC by ivan-mashonskiy

2023-09-12 14:52 UTC, xrtm000 approved these changes

2023-09-21 13:07 UTC, vsuharnikov requested changes

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/api/http/TransactionsApiRoute.scala
> +    }
Let's enable the transactions broadcasting for light nodes, it is useful and nothing prevents from doing this

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/database/RocksDBWriter.scala
> +  override protected def doRollback(targetHeight: Int): Seq[(Block, ByteStr, Option[BlockSnapshot])] = {
There is a type `DiscardedBlocks = (Block, ByteStr, Option[BlockSnapshot])`. 
I still prefer case classes for public methods, because IDE always tries to expand type aliases.
But type aliases are good too. They help searching usages in IDE.

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/database/RocksDBWriter.scala
> +  override def prevStateHash(refId: Option[ByteStr]): ByteStr = {
Actually, it looks like `lastStateHash`, because we look on the current height or on a specified liquid block. Isn't it?

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/Application.scala
> +    } else UtxPool.NoOp
Just wondering why don't write instead:
```
val utxStorage = if (settings.enableLightMode) UtxPool.NoOp else {
  new UtxPoolImpl(time, blockchainUpdater, settings.utxSettings, settings.maxTxErrorLogSize, settings.minerSettings.enable, utxEvents.onNext)
}
```
? When "if" branch has a negation, thinking about the "else" branch breaks a brain, because you have to think about a double negation (`!!settings.enableLightMode`).

There must be the reason, and I would like to know it.

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/network/DiscardingHandler.scala
> +      logDiscarding(ctx, code)
Do we really need to log this? I mean this is normal behavior of a full node.

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/network/DiscardingHandler.scala
> +    case RawBytes(code @ (TransactionSpec.messageCode | PBTransactionSpec.messageCode), _) if !lastReadiness().contains(true) || isLightMode =>
I think we need to re-broadcast transactions even this is a light node, because imagine, you are a miner and all your connections are light nodes. This could happen, because the light node is an appropriate choice for most projects on blockchain (hope there will be much more projects 🤞).

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/network/MessageCodec.scala
> +    case k: KnownPeers            => out.add(RawBytes(PeersSpec.messageCode, PeersSpec.serializeData(k)))
How about:
```scala
object RawBytes {
  def from[T <: AnyRef](spec: MessageSpec[T], message: T): RawBytes = RawBytes(spec.messageCode, spec.serializeData(message))
  // ...
}

RawBytes.from(PeersSpec, k)
``` 
? 🤔

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/network/MessageCodec.scala
> +    case k: KnownPeers            => out.add(RawBytes(PeersSpec.messageCode, PeersSpec.serializeData(k)))
Also you might want to move `out.add` outside `match`, this will reduce duplication.

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/network/RxExtensionLoader.scala
> +    def onSnapshot(state: State, ch: Channel, snapshot: BlockSnapshot): State = {
This function shares a functionality with `onBlock`. I think we could make them simpler, if extract a common part (errors and changing the state) to a separate function. How can it be:
1. Create an updated instance of `LoaderState.ExpectingBlocksWithSnapshots` based on received data (block or snapshot), update structures and write all required data to channels
2. A common part: look into the updated `LoaderState.ExpectingBlocksWithSnapshots` and:
   1. If we received all blocks and snapshots - finish the loading of extension.
   2. If not: 
      1. Scheduler an error, that we didn't receive blocks and snapshots. We could use a common error message format, e.g.: `"Timeout loading blocks={} and snapshots={}"`. We also can limit the shown number of blocks and snapshots by 1 and add "..." if there are more blocks or snapshots. Actually, I think, just 1 not received block and 1 snapshot are enought: `"Timeout loading block={} and snapshot={}"`
      2. Use `state.withLoaderState` to return a new state.

2023-09-21 13:07 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/network/TransactionPublisher.scala
> +  val NoOp: TransactionPublisher = { (_, _) => Future(TracedResult.wrapValue(true)) }
```suggestion
  val NoOp: TransactionPublisher = { (_, _) => Future.successful(TracedResult.wrapValue(true)) }
```
😉

2023-09-25 17:15 UTC, vsuharnikov approved these changes

2023-10-06 09:44 UTC, DrBlast approved these changes

2023-10-06 10:04 UTC, phearnot approved these changes

2023-10-06 10:05 UTC, merged

2023-10-06 13:40 UTC, xrtm000 approved these changes