NODE-2596 Optimised active leases
wavesplatform/Waves pull request #3884
Opened 2023-09-29 14:41 UTC by xrtm000

2023-10-05 15:33 UTC, ivan-mashonskiy approved these changes

2023-10-06 10:33 UTC, vsuharnikov approved these changes

2023-11-06 07:57 UTC, phearnot requested changes
- Instead of copying lease details to sender and recipient accounts, store only lease IDs (just like for address transactions).
- Add a test which checks that cancelled leases are excluded from the response.
- Add a test to check if rollback works (for both active and cancelled leases).

2023-11-06 07:57 UTC, phearnot commented on node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
> +      leaseStatesAreStoredByAddress: Boolean
unused?

2023-11-09 06:43 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/api/common/CommonAccountsApi.scala
> +      leaseStatesAreStoredByAddress: Boolean
Removed

2023-11-29 10:00 UTC, DrBlast approved these changes

2023-11-30 08:32 UTC, phearnot approved these changes

2023-11-30 08:33 UTC, merged