NODE-2503 Better transaction asset payment errors
wavesplatform/Waves pull request #3890
Opened 2023-10-09 08:44 UTC by xrtm000

2023-10-11 14:27 UTC, DrBlast requested changes

2023-10-11 14:27 UTC, DrBlast commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/TransactionAssetChecksTest.scala
> +  }
add the same tests for ethereum invoke and transfer

2023-10-13 07:32 UTC, vsuharnikov commented on node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
> +              }
Why just don't use `.collectFirst` which works the same way but with less code?
```suggestion
            _ <- citx.payments
              .collectFirst { 
                case Payment(_, IssuedAsset(id)) => InvokeDiffsCommon.checkAsset(blockchain, id).swap
              }
```

2023-10-16 08:38 UTC, ivan-mashonskiy approved these changes

2023-10-17 12:59 UTC, xrtm000 commented on node/src/main/scala/com/wavesplatform/state/diffs/CommonValidation.scala
> +              }
Because it's not the same. 
`.collectFirstSome` allows here to collect error from `Left`, avoiding `Either` structure.

2023-10-17 14:11 UTC, xrtm000 commented on node/src/test/scala/com/wavesplatform/state/diffs/ci/TransactionAssetChecksTest.scala
> +  }
Done

2023-11-07 08:30 UTC, DrBlast approved these changes

2023-11-10 14:09 UTC, vsuharnikov approved these changes

2023-11-15 10:55 UTC, phearnot approved these changes

2023-11-27 06:46 UTC, merged